{% set name = "tomopy" %}
{% set version = "1.1.2" %}
{% set sha256 = "0ababe6dec3aaf78af4bb646b3865845cf45a0884207ed9aafacca03729933d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  script: |
    export C_INCLUDE_PATH=$PREFIX/include  # [not win]
    set C_INCLUDE_PATH=%PREFIX%\\include  # [win]
    {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
  build:
    - mkl-devel
    - {{ compiler('c')}}
    - {{ compiler('cpp')}}
  run:
    - python
    - dxchange
    - mkl
    - mkl_fft
    - numexpr
    - numpy
    - pywavelets
    - scikit-image
    - scipy
    - six

test:
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util

app:
  own_environment: True

about:
  home: http://tomopy.readthedocs.io
  license: BSD 3-Clause
  summary: Tomographic reconstruction in Python.
  dev_url: https://github.com/tomopy/tomopy
  doc_url: https://tomopy.readthedocs.io
