{% set version = "1.9.1" %}
{% set build = 3 %}

# Set CUDA related variables
{% if linux64 and cuda_compiler_version != "None" %}
{% set cuda_build_prefix = "cuda" + cuda_compiler_version|string %}
{% set cuda_flag = "enable" %}
{% else %}
{% set cuda_build_prefix = "" %}
{% set cuda_flag = "disable" %}
{% set build = build + 100 %}
{% endif %}

# Set FFT related variables
{% if win or osx or linux32 or linux64 %}
{% set mkl_flag = "enable" %}
{% set libfft = "mkl-devel" %}
{% set pyfft = "mkl_fft" %}
{% else %}
{% set mkl_flag = "disable" %}
{% set libfft = "nomkl" %}
{% set pyfft = "nomkl" %}
{% endif %}

# Set OpenCV related variables
{% set opencv_flag = "disable" %}

package:
    name: tomopy
    version: {{ version }}

source:
  # git checkout because PTL submodule is not included in GitHub tarball
  - git_url: https://github.com/tomopy/tomopy.git
    git_rev: {{ version }}

build:
  number: {{ build }}
  string: "{{ cuda_build_prefix }}py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  skip: true  # [py2k]
  merge_build_host: True  # [win]
  script:
    {{ PYTHON }} -m pip install .
    --no-deps --ignore-installed --no-index --no-cache-dir -vv
    --install-option="-GNinja"
    --install-option="--{{ cuda_flag }}-cuda"
    --install-option="-DCUDA_TOOLKIT_ROOT_DIR=${CUDA_HOME}"
    --install-option="--{{ mkl_flag }}-mkl"
    --install-option="--{{ opencv_flag }}-opencv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - pip
    - python
    - {{ libfft }}
    - {{ pyfft }}
    - scikit-build >=0.10.1
    - setuptools_scm_git_archive
  run:
    - {{ pyfft }}
    - numexpr
    - numpy >1.12
    - pywavelets
    - python
    - scikit-image
    - scipy
    - setuptools
    - tifffile
  run_constrained:
    - astra-toolbox >1.8

test:
  requires:
    - pytest
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - unset CUDA_VERSION  # [unix]
    - pytest test -vs

app:
  own_environment: True

about:
  home: http://tomopy.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Tomographic reconstruction in Python.'
  description: |
    TomoPy is an open-source Python package for tomographic data
    processing and image reconstruction.
  doc_url: http://tomopy.readthedocs.io
  dev_url: https://github.com/tomopy/tomopy
